<?php

namespace app\api\model\kl;

use app\common\model\TimeModel;

/**
 * 店铺资料 model
 */
class ErpCustomerModel extends TimeModel
{
    protected $connection = 'sqlsrv2';

    // 表名
    protected $name = 'Customer';

    protected $schema = [
        'CustomerId' => 'nvarchar',
        'CustomerCode' => 'nvarchar',
        'CustomerName' => 'nvarchar',
        'Abbrev' => 'nvarchar',
        'Address' => 'nvarchar',
        'Tel1' => 'nvarchar',
        'Tel2' => 'nvarchar',
        'ZipCode' => 'nvarchar',
        'Fax' => 'nvarchar',
        'Contact' => 'nvarchar',
        'MathodId' => 'bigint',
        'Email' => 'nvarchar',
        'PCustomerId' => 'nvarchar',
        'ShutOut' => 'bit',
        'StateId' => 'bigint',
        'State' => 'nvarchar',
        'CityId' => 'bigint',
        'City' => 'nvarchar',
        'DistrictId' => 'bigint',
        'District' => 'nvarchar',
        // 'RegionId' => 'bigint',
        'RoleCategoryId' => 'bigint',
        'BranchId' => 'bigint',
        'AccountId' => 'nvarchar',
        'CreateTime' => 'datetime',
        'CreateUserId' => 'bigint',
        'CreateUserName' => 'nvarchar',
        'UpdateTime' => 'datetime',
        'UpdateUserId' => 'bigint',
        'UpdateUserName' => 'nvarchar',
        // 'Version' => 'timestamp', //这个很坑，不用填入 $schema
        'IsB2B' => 'bit',
        'B2BDzPhone' => 'nvarchar',
        'B2BPCustomerID' => 'nvarchar',
        'OrderAmount' => 'decimal',
        'IsOffline' => 'bit',
        'B2BDzName' => 'nvarchar',
        'AllocationGroup' => 'nvarchar',
        'StoreArea' => 'decimal',
        'SalesmanGroup' => 'nvarchar',
        'PosSalesmanControl' => 'bit',
        'RoundingMode' => 'int',
        'RoundingType' => 'int',
        'RoundingUnit' => 'int',
        'PosPrintNum' => 'int',
        'ShopNature' => 'int',
        'IsCustReceiptDelivery' => 'bit',
        'IsInCustomer' => 'bit',
        'OnlyQrReward' => 'bit',
        'PrintIndex' => 'int',
        'SendGoodsGroup' => 'varchar',
        'Longitude' => 'decimal',
        'Dimension' => 'decimal',
        'ShopownerUserId' => 'bigint',
        'ClerkUserId' => 'bigint',
        'AllowNegativeInventory' => 'bit',
        'IsPosStockCheck' => 'bit',
        'PosPriceId' => 'int',
        'seller_name' => 'nvarchar',
        'store_id' => 'nvarchar',
        'Img' => 'varchar',
        'QrCodePrintType' => 'int',
        'OpeningDate' => 'datetime',
        'CompletionDate' => 'datetime',
        'IsNetSale' => 'bit',
        'NetSaleCustomerId' => 'nvarchar',
        'IsShowNearbyCus' => 'bit',
        'SaleWarehouseId' => 'nvarchar',
        'IsShowSalePrice' => 'bit',
        'GroupId' => 'bigint',
        'GroupName' => 'nvarchar',
        'IsAllowFreeReturn' => 'bit',
        'SettlementRatio' => 'decimal',
        'ChargeMan' => 'nvarchar',
        'IsPool' => 'bit',
        'Remark' => 'nvarchar',
        'CustomItem1' => 'nvarchar',
        'CustomItem2' => 'nvarchar',
        'CustomItem3' => 'nvarchar',
        'CustomItem4' => 'nvarchar',
        'CustomItem5' => 'nvarchar',
        'CustomItem6' => 'nvarchar',
        'CustomItem7' => 'nvarchar',
        'CustomItem8' => 'nvarchar',
        'CustomItem9' => 'nvarchar',
        'CustomItem10' => 'nvarchar',
        'CustomItem11' => 'nvarchar',
        'CustomItem12' => 'nvarchar',
        'CustomItem13' => 'nvarchar',
        'CustomItem14' => 'nvarchar',
        'CustomItem15' => 'nvarchar',
        'CustomItem16' => 'nvarchar',
        'CustomItem17' => 'nvarchar',
        'CustomItem18' => 'nvarchar',
        'CustomItem19' => 'nvarchar',
        'CustomItem25' => 'nvarchar',
        'CustomItem26' => 'nvarchar',
        'CustomItem100' => 'nvarchar',
        'WxServiceType' => 'int',
        'ContractBeginDate' => 'datetime',
        'ContractEndDate' => 'datetime',
        'PosDpPriceId' => 'int',
        'DeliveryRoundingMode' => 'int',
        'DeliveryRoundingType' => 'int',
        'DeliveryRoundingUnit' => 'int',
        'IsNotReturnDiscount' => 'bit',
        'CustomerGrade' => 'nvarchar',
        'EvaluationID' => 'nvarchar',
        'B2BMiNiWeiXinID' => 'nvarchar',
        'B2BPostionDZ' => 'nvarchar',
        'B2BPostionDY' => 'nvarchar',
        'IsAllowShopPickUp' => 'bit',
        'IsServiceBooking' => 'bit',
        'UnionPrintIndex' => 'int',
        'IsInstructionCustOutbound' => 'bit',
        'StreetId' => 'bigint',
        'Street' => 'nvarchar',
        'CustomerGradeId' => 'bigint',
        'StockGroup' => 'nvarchar',
        'BalanceUseGroupId' => 'bigint',
        'IsPosRetailInProportion' => 'bit',
        'LineOnName' => 'nvarchar',
        'CompanyId' => 'nvarchar',
        'IsSync' => 'bit',
        'SupplyStockType' => 'int',
        'IntegralDiscount' => 'decimal',
        'BluetoothPrintMac' => 'nvarchar',
        'CustReceiptDeliveryDay' => 'int',
        'IsEc_GetE3Stock' => 'bit',
        'DepartmentId' => 'bigint',
        'PosMaxReturnDay' => 'int',
        'IsPosVipInput' => 'bit',
        'IsCustOutCust' => 'bit',
        'IsGetDefaultCustStock' => 'bit',
        'VIPNo' => 'nvarchar',
        'IsDeliveryAutoCompleted' => 'bit',
        'IsGetDefaultVIPCustStock' => 'bit',
        'IsBeSale' => 'bit',
        'IsAllowPreSale' => 'bit',
    ];

    const INSERT = [
        'BranchId' => '2',
        'CreateUserId' => '29',
        'CreateUserName' => '辛斌',
        'UpdateUserId' => '29',
        'UpdateUserName' => '辛斌',
    ];

}