<?php

namespace app\api\model\kl;

use app\common\model\TimeModel;

/**
 * 货品资料 model
 */
class ErpGoodsModel extends TimeModel
{
    protected $connection = 'sqlsrv2';

    // 表名
    protected $name = 'Goods';

    protected $schema = [
        // 'GoodsId' => 'bigint', 
        'GoodsNo' => 'nvarchar',
        'GoodsName' => 'nvarchar',
        'Status' => 'nvarchar',
        'GoodsCode' => 'nvarchar',
        'BrandId' => 'bigint',
        'BrandName' => 'nvarchar',
        'UnitPrice' => 'decimal',
        'GoodsType' => 'nvarchar',
        'CategoryId' => 'bigint',
        'CategoryName' => 'nvarchar',
        'TimeCategoryId' => 'bigint',
        'TimeCategoryName' => 'nvarchar',
        'StyleCategoryId' => 'bigint',
        'StyleCategoryName' => 'nvarchar',
        'RoleCategoryId' => 'bigint',
        'RoleCategory' => 'nvarchar',
        'CustCategoryId' => 'bigint',
        'CustCategoryName' => 'nvarchar',
        'DiscountTypeId' => 'bigint',
        'DiscountTypeName' => 'nvarchar',
        'IsHasSku' => 'bit',
        'CreateTime' => 'datetime',
        'CreateUserId' => 'bigint',
        'CreateUserName' => 'nvarchar',
        'UpdateTime' => 'datetime',
        'UpdateUserId' => 'bigint',
        'UpdateUserName' => 'nvarchar',
        'GoodsRemark' => 'nvarchar',
        'DepositRatio' => 'decimal',
        'SupplyId' => 'nvarchar',
        'IsAdvance' => 'bit',
        'CategoryId1' => 'bigint',
        'CategoryName1' => 'nvarchar',
        'CategoryId2' => 'bigint',
        'CategoryName2' => 'nvarchar',
        'TimeCategoryId1' => 'bigint',
        'TimeCategoryName1' => 'nvarchar',
        'TimeCategoryId2' => 'bigint',
        'TimeCategoryName2' => 'nvarchar',
        'StyleCategoryId1' => 'bigint',
        'StyleCategoryName1' => 'nvarchar',
        'StyleCategoryId2' => 'bigint',
        'StyleCategoryName2' => 'nvarchar',
        'CustomItem1' => 'nvarchar',
        'CustomItem2' => 'nvarchar',
        'CustomItem3' => 'nvarchar',
        'CustomItem4' => 'nvarchar',
        'CustomItem5' => 'nvarchar',
        'CustomItem6' => 'nvarchar',
        'CustomItem7' => 'nvarchar',
        'CustomItem8' => 'nvarchar',
        'CustomItem9' => 'nvarchar',
        'CustomItem10' => 'nvarchar',
        'CustomItem11' => 'nvarchar',
        'CustomItem12' => 'nvarchar',
        'CustomItem13' => 'nvarchar',
        'CustomItem14' => 'nvarchar',
        'CustomItem15' => 'nvarchar',
        'CustomItem16' => 'nvarchar',
        'CustomItem17' => 'nvarchar',
        'CustomItem18' => 'nvarchar',
        'CustomItem19' => 'nvarchar',
        'CustomItem20' => 'nvarchar',
        'CustomItem21' => 'nvarchar',
        'CustomItem22' => 'nvarchar',
        'CustomItem23' => 'nvarchar',
        'CustomItem24' => 'nvarchar',
        'HeelMan' => 'nvarchar',
        'Designer' => 'nvarchar',
        'OnLineGoods' => 'nvarchar',
        'Unit' => 'nvarchar',
        'xinbin' => 'nvarchar',
        'CareRemark' => 'nvarchar',
        'SupplyGoodsNo' => 'nvarchar',
        'BatchId' => 'bigint',
        'BatchName' => 'nvarchar',
        'BatchDay' => 'int',
        'BranchId' => 'bigint',
        'IsOnlineGoods' => 'bit',
        'TaxRate' => 'decimal',
        'Sex' => 'nvarchar',
        'sMinQuantity' => 'decimal',
        'IsOnlyShopPickUp' => 'bit',
        'IsDecimal' => 'bit',
        'Weight' => 'decimal',
        'IsOverseas' => 'bit',
        'RemindDay' => 'int',
        'RetailNum' => 'int',
        'IsPresent' => 'int',
        'ShowColorText' => 'nvarchar',
        'ShowSpecText' => 'nvarchar',
        'CustCategoryId1' => 'bigint',
        'CustCategoryName1' => 'nvarchar',
        'CustCategoryId2' => 'bigint',
        'CustCategoryName2' => 'nvarchar',
        'CodingCode' => 'nvarchar',
        'CodingCodeText' => 'nvarchar',
        'WorkflowId' => 'bigint',
    ];

    const INSERT = [
        'BranchId' => '2',
        'CreateUserId' => '29',
        'CreateUserName' => '辛斌',
        'UpdateUserId' => '29',
        'UpdateUserName' => '辛斌',
    ];

}